### ISSUE TITLE
Please add support for Play 2.4

### ISSUE THREAD

**Issue by cmoro-deusto** [tuxBurner/play-neo4jplugin#16]
Plugin fails to start using Play 2.4:

```
play.api.UnexpectedException: Unexpected exception[ConfigurationException: Guice configuration errors:

1) Could not find a suitable constructor in neo4jplugin.Neo4JPlugin. Classes must have either one (and only one) constructor annotated with @Inject or a zero-argument constructor that is not private.
  at neo4jplugin.Neo4JPlugin.class(Neo4JPlugin.java:21)
  while locating neo4jplugin.Neo4JPlugin

1 error]
	at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(DevServerStart.scala:165) ~[play-server_2.10-2.4.0.jar:2.4.0]
	at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(DevServerStart.scala:121) ~[play-server_2.10-2.4.0.jar:2.4.0]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.10.5.jar:na]
	at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1.apply(DevServerStart.scala:121) ~[play-server_2.10-2.4.0.jar:2.4.0]
	at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1.apply(DevServerStart.scala:119) ~[play-server_2.10-2.4.0.jar:2.4.0]
	at scala.util.Success.flatMap(Try.scala:200) ~[scala-library-2.10.5.jar:na]
	at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1.apply(DevServerStart.scala:119) ~[play-server_2.10-2.4.0.jar:2.4.0]
	at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1.apply(DevServerStart.scala:111) ~[play-server_2.10-2.4.0.jar:2.4.0]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library-2.10.5.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library-2.10.5.jar:na]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402) ~[na:1.8.0_40]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[na:1.8.0_40]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[na:1.8.0_40]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) ~[na:1.8.0_40]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[na:1.8.0_40]
Caused by: com.google.inject.ConfigurationException: Guice configuration errors:

1) Could not find a suitable constructor in neo4jplugin.Neo4JPlugin. Classes must have either one (and only one) constructor annotated with @Inject or a zero-argument constructor that is not private.
  at neo4jplugin.Neo4JPlugin.class(Neo4JPlugin.java:21)
  while locating neo4jplugin.Neo4JPlugin

1 error
	at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:1042) ~[guice-4.0.jar:na]
	at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:1001) ~[guice-4.0.jar:na]
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1051) ~[guice-4.0.jar:na]
	at play.api.inject.guice.GuiceInjector.instanceOf(GuiceInjectorBuilder.scala:321) ~[play_2.10-2.4.0.jar:2.4.0]
	at play.api.Plugins$$anonfun$loadPlugins$1.apply(Plugins.scala:89) ~[play_2.10-2.4.0.jar:2.4.0]
	at play.api.Plugins$$anonfun$loadPlugins$1.apply(Plugins.scala:87) ~[play_2.10-2.4.0.jar:2.4.0]
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244) ~[scala-library-2.10.5.jar:na]
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244) ~[scala-library-2.10.5.jar:na]
	at scala.collection.immutable.List.foreach(List.scala:318) ~[scala-library-2.10.5.jar:na]
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244) ~[scala-library-2.10.5.jar:na]
	at scala.collection.AbstractTraversable.map(Traversable.scala:105) ~[scala-library-2.10.5.jar:na]
	at play.api.Plugins$.loadPlugins(Plugins.scala:87) ~[play_2.10-2.4.0.jar:2.4.0]
	at play.api.Plugins$$anonfun$apply$4.apply(Plugins.scala:100) ~[play_2.10-2.4.0.jar:2.4.0]
	at play.api.Plugins$$anonfun$apply$4.apply(Plugins.scala:100) ~[play_2.10-2.4.0.jar:2.4.0]
	at play.api.Plugins.thePlugins$lzycompute(Plugins.scala:59) ~[play_2.10-2.4.0.jar:2.4.0]
	at play.api.Plugins.thePlugins(Plugins.scala:59) ~[play_2.10-2.4.0.jar:2.4.0]
	at play.api.Plugins.length(Plugins.scala:60) ~[play_2.10-2.4.0.jar:2.4.0]
	at scala.collection.IndexedSeqLike$class.iterator(IndexedSeqLike.scala:91) ~[scala-library-2.10.5.jar:na]
	at play.api.Plugins.iterator(Plugins.scala:57) ~[play_2.10-2.4.0.jar:2.4.0]
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72) ~[scala-library-2.10.5.jar:na]
	at play.api.Plugins.foreach(Plugins.scala:57) ~[play_2.10-2.4.0.jar:2.4.0]
	at play.api.Play$$anonfun$start$1.apply$mcV$sp(Play.scala:91) ~[play_2.10-2.4.0.jar:2.4.0]
	at play.api.Play$$anonfun$start$1.apply(Play.scala:91) ~[play_2.10-2.4.0.jar:2.4.0]
	at play.api.Play$$anonfun$start$1.apply(Play.scala:91) ~[play_2.10-2.4.0.jar:2.4.0]
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21) ~[play_2.10-2.4.0.jar:2.4.0]
	at play.api.Play$.start(Play.scala:90) ~[play_2.10-2.4.0.jar:2.4.0]
	at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(DevServerStart.scala:156) ~[play-server_2.10-2.4.0.jar:2.4.0]
	... 14 common frames omitted
```

Maybe this error is related to the new Dependency Injection provided by Guice in Play 2.4.

Could you please add support for this version?

**Comment by tuxBurner** [comment]
Hi @cmoro-deusto thx for reporting this.

I am on it to get a release which is working with play2.4

**Comment by cmoro-deusto** [comment]
@tuxBurner thanks a lot. I cloned the repo and started the migration as well (even upgrading dependencies when possible), but if you are on it, I will wait for it. Just let me know if I can help you with the migration or with the testing before release!

**Comment by tuxBurner** [comment]
@cmoro-deusto oh nice :)
I <3 if you could help me on this.
I started yesterday a new branch: https://github.com/tuxBurner/play-neo4jplugin/tree/play2.4
I is still not working just a setup for testing it.
Feel free to file me a pull request on this.
I also tried to lift spring-data-neo4j a while a go, but there are class loader problems.

**Comment by cmoro-deusto** [comment]
@tuxBurner yep, I run into classloader issues on my try to upgrade, only to find your bug reports later on Spring Data's Jira :) 

Will fork your repo and work on the new branch

**Comment by cmoro-deusto** [comment]
@tuxBurner Investigating further on this issue, looks like plugins are somewhat deprecated on Play 2.4. They don't say that explicitly anywhere AFAIK, but everywhere I look they suggest creating a Guice Module instead of a Plugin...

**Comment by tuxBurner** [comment]
@cmoro-deusto, yep this what i found out to yesterday, and than the bed was calling :)
I think the best way to do this is to make it a module. We also should consider moving the ServiceProvider to a injectable service.

**Comment by cmoro-deusto** [comment]
@tuxBurner there's another problem... Play 2.4 now uses v4.1.6 of Spring Context, Core and Beans.

[Play 2.4 Dependencies](https://github.com/playframework/playframework/blob/2.4.x/framework/project/Dependencies.scala)

Would this plugin, even if turned into a guice module, work with the current approach?

**Comment by cmoro-deusto** [comment]
OK, I think I managed to get it to work... testing now.

**Comment by cmoro-deusto** [comment]
OK, it works in my test app. Cannot try or adapt your example right now (gotta leave). Created a PR 

https://github.com/tuxBurner/play-neo4jplugin/pull/17

**Comment by antonini** [comment]
+1

**Comment by cmoro-deusto** [comment]
Thanks very much @tuxBurner!

**Comment by antonini** [comment]
@tuxBurner I'll take a look! Tks! :)
