### ISSUE TITLE
Upgrade to SDN 4.1

### ISSUE THREAD

**Issue by unterstein** [tuxBurner/play-neo4jplugin#28]
Hi,

currently working on upgrading to SDN 4.1, current status is here: https://github.com/tuxBurner/play-neo4jplugin/tree/features/sdn41

Compiles and works, except transaction handling. Work is progress at this point. Should be ready tomorrow :-)

Cheers
Johannes

**Comment by unterstein** [comment]
Solved transactional issues, but still some FIXMEs inside. Currently talking to @jexp to solve this.

**Comment by DwayneSmurdon** [comment]
I HAVE successfully installed and ran the example on the "1.5.1-SNAPSHOT" build.  But, I am trying to reinstall it and I'm having a problem.

warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: default#dwayne_2.11;0.1-SNAPSHOT: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]
[warn]  Note: Unresolved dependencies path:
[warn]          default:dwayne_2.11:0.1-SNAPSHOT
[warn]            +- play-2-4-neo4j-template:play-2-4-neo4j-template_2.11:1.0-SNAPSHOT
sbt.ResolveException: unresolved dependency: default#dwayne_2.11;0.1-SNAPSHOT: not found
        at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:291)
        at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:188)
        at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:165)
        at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:155)
        at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:155)
        at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:132)
        at sbt.IvySbt.sbt$IvySbt$$action$1(Ivy.scala:57)
        at sbt.IvySbt$$anon$4.call(Ivy.scala:65)
        at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:98)
        at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:81)
        at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:102)
        at xsbt.boot.Using$.withResource(Using.scala:11)
        at xsbt.boot.Using$.apply(Using.scala:10)
        at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:62)
        at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:52)
        at xsbt.boot.Locks$.apply0(Locks.scala:31)
        at xsbt.boot.Locks$.apply(Locks.scala:28)
        at sbt.IvySbt.withDefaultLogger(Ivy.scala:65)
        at sbt.IvySbt.withIvy(Ivy.scala:127)
        at sbt.IvySbt.withIvy(Ivy.scala:124)
        at sbt.IvySbt$Module.withModule(Ivy.scala:155)
        at sbt.IvyActions$.updateEither(IvyActions.scala:165)
        at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1369)
        at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1365)
        at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$87.apply(Defaults.scala:1399)
        at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$87.apply(Defaults.scala:1397)
        at sbt.Tracked$$anonfun$lastOutput$1.apply(Tracked.scala:37)
        at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1402)
        at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1396)
        at sbt.Tracked$$anonfun$inputChanged$1.apply(Tracked.scala:60)
        at sbt.Classpaths$.cachedUpdate(Defaults.scala:1419)
        at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1348)
        at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1310)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
        at sbt.std.Transform$$anon$4.work(System.scala:63)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.Execute.work(Execute.scala:235)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
[error](root/*:update) sbt.ResolveException: unresolved dependency: default#dwayne_2.11;0.1-SNAPSHOT: not found

Environment:
- I'm on windows 10 and under cygwin.
- "dwayne" is my username in my cygwin shell

What I've done:

I've done "activator new pd-data-tmp2" and then extracted (and replaced all) files in that directory from the zip I downloaded (but only the contents of: play-neo4jplugin-master\examples\play-2.4-neo4j-template).  

I then have commented out this line in build.sbt (because I don't have a local repo and even if I did, I would have to change this to file:///)
//resolvers += "Local Maven Repository" at "file://"+Path.userHome.absolutePath+"/.m2/repository"

Why would sbt be trying to resolve: default#dwayne_2.11;0.1-SNAPSHOT

I have also tried simply creating a directory pd-data-tmp2, extracting the same example files, copying over activator, activator.bat, and activator-launch-1.2.12.jar.  I get the same result.

Any thoughts?

-Dwayne

**Comment by unterstein** [comment]
Hi @DwayneSmurdon,

the release SNAPSHOT is not the version of the linked branch for this issue. If you want to test this, you could checkout the features/sdn41 (https://github.com/tuxBurner/play-neo4jplugin/tree/features/sdn41) branch and do a "sbt publish" and then retry this in your project. If you want to work with sbt/ivy snapshots, it would be good, if you mark the dependency to the plugin as changing()

example:

```
libraryDependencies += "com.github.tuxBurner" %% "play-neo4jplugin" % "1.5.0" changing()
```

Kind regards
Johannes

**Comment by DwayneSmurdon** [comment]
Hi @unterstein,

Thanks for the response. I moved over to unterstein/play-2.5-sdn-4.1 actually.  I've been able to get that running and have implemented custom repositories and models successfully.

Hopefully this will be a fairly "stable" component in our stack.  play, neo4j, and sdn have all had some pretty large changes since I originally started trying to integrate them, not to mention changes that arrived in Java 8, Scala, and sbt.  So, I'm appreciative of the efforts from you and @tuxBurner, as well as the SDN team.  

-Dwayne
