### ISSUE TITLE
Shutdown hook

### ISSUE THREAD

**Issue by unterstein** [tuxBurner/play-neo4jplugin#6]
Hi Sepp,

i get the following exception during shutdown in production:

[warn] play - Error stopping plugin
org.springframework.beans.factory.BeanCreationNotAllowedException: Error creating bean with name 'neo4JServiceProvider': Singleton bean creation not allowed while the singletons of this factory are in destruction (Do not request a bean from a BeanFactory in a destroy method implementation!)
at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:210) ~[org.springframework.spring-beans-3.2.2.RELEASE.jar:3.2.2.RELEASE]
at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:292) ~[org.springframework.spring-beans-3.2.2.RELEASE.jar:3.2.2.RELEASE]
at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:198) ~[org.springframework.spring-beans-3.2.2.RELEASE.jar:3.2.2.RELEASE]
at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:273) ~[org.springframework.spring-beans-3.2.2.RELEASE.jar:3.2.2.RELEASE]
at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1125) ~[org.springframework.spring-context-3.2.2.RELEASE.jar:3.2.2.RELEASE]
at neo4jplugin.Neo4JPlugin.get(Neo4JPlugin.java:105) ~[com.github.tuxBurner.play-neo4jplugin_2.10-1.1.1.jar:1.1.1]

and you posted me the following link:

http://stackoverflow.com/questions/5891032/in-a-spring-bean-is-it-possible-to-have-a-shutdown-method-which-can-use-transact

Have a lot of fun ;-)
Jo

**Comment by unterstein** [comment]
obsolete in current version
